### ISSUE TITLE
Check if the entity_id is null

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#186]
I know that this maybe is silly, but if the `entity_id` is `null` `triage` fails with the following error:

```
WARNING:root:Starting train/test for 1 out of 11: train range: 2014-01-01 00:00:00 to 2014-04-01 00:00:00
WARNING:root:3 month
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    experiment.run()
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 334, in run
    self.catwalk()
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/singlethreaded.py", line 88, in catwalk
    train_matrix_columns=train_store.columns(),
  File "/usr/local/lib/python3.6/site-packages/catwalk/predictors.py", line 253, in predict
    misc_db_parameters
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/site-packages/catwalk/predictors.py", line 159, in _write_to_db
    entity_id=int(entity_id),
ValueError: cannot convert float NaN to integer
```

Maybe, we should add a note in the `README` or drop those rows with a warning (or both)

**Comment by thcrock** [comment]
So this comes from the source data? If so, I agree that it should do both. Or maybe they should be filtered out before matrix time? It sounds like there's no reason for them to show up in any matrices.

**Comment by thcrock** [comment]
Now that we have the validation framework in place, I think 'check the source to make sure no entity ids are null' is a reasonable validation to add.

https://github.com/dssg/triage/blob/master/src/triage/experiments/validate.py

**Comment by thcrock** [comment]
Well, now that there's no events table anymore, this should probably happen right after the cohort is built by querying the cohort table
