### ISSUE TITLE
entity_id should not be hardcoded

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#189]
Using:

```
      feature_aggregations:
        -
          # Number of violations of a specific code and proportion, grouped by entity
          prefix: 'violations'
          from_obj: 'cleaned.violations'
          knowledge_date_column: 'knowledge_date'

          categoricals:
            -
              column: 'violation_code'
              choice_query: 'select distinct violation_code from cleaned.violations'
              metrics:
                - 'sum'
                - 'avg'

          intervals:
            - '1 y'

          groups:
            - 'entity_id'

        -  # inspections in the last year associated with this entity
          prefix: 'inspections'
          from_obj: 'cleaned.inspections'
          knowledge_date_column: 'date'
          aggregates:
            -
                quantity: '*'
                metrics:
                    - 'count'
          intervals:
            - '1 y'

          groups:
            - 'license_num'

```

It will generate the `features` tables, but then (I presume, when `triage` tries to generate the matrices) gives you the following error:

```
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    experiment.run()
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 333, in run
    self.build_matrices()
  File "/usr/local/lib/python3.6/site-packages/triage/experiments/singlethreaded.py", line 18, in build_matrices
    self.planner.build_all_matrices(self.matrix_build_tasks)
  File "/usr/local/lib/python3.6/site-packages/architect/planner.py", line 180, in build_all_matrices
    self.builder.build_all_matrices(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/architect/builders.py", line 19, in build_all_matrices
    self.build_matrix(**task_arguments)
  File "/usr/local/lib/python3.6/site-packages/architect/builders.py", line 256, in build_matrix
    matrix_uuid
  File "/usr/local/lib/python3.6/site-packages/architect/builders.py", line 391, in write_features_data
    self.write_to_csv(features_query, csv_name)
  File "/usr/local/lib/python3.6/site-packages/architect/builders.py", line 418, in write_to_csv
    cur.copy_expert(copy_sql, matrix_csv)
psycopg2.ProgrammingError: column r.entity_id does not exist
LINE 14:             ON ed.entity_id = r.entity_id AND
                                       ^
HINT:  Perhaps you meant to reference the column "ed.entity_id".
```

I suppose this is related to the fact that tries to join one the tables in the schema `features` with the  `events_table`

**Comment by thcrock** [comment]
The error thrown here has to do with how groups operate - just license_num is not enough, you need both license_num and entity_id. Since this issue was created, there is a validation that covers this: https://github.com/dssg/triage/blob/master/src/triage/experiments/validate.py#L160-L163

The question of whether or not we should force the column to be called entity_id is addressed here:
https://github.com/dssg/triage/issues/276

So I don't think there's anything left here and I'm closing the issue.
