### ISSUE TITLE
Serialization fails with listener attached to sqlalchemy in Multicoreexperiment

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#484]
When trying to run `triage` in a `MulticoreExperiment` I am getting the following error:

```
root 31/10/2018 06:16:59 PM DEBUG 1 feature_generators.py 334: ---------------------
root 31/10/2018 06:16:59 PM DEBUG 1 feature_generators.py 340: ---------FEATURE GENERATION------------
root 31/10/2018 06:16:59 PM DEBUG 1 feature_generators.py 347: ---------------------
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py:4385: SAWarning: Textual column expression 'entity_id' should be explicitly declared with text('entity_id'), or use column('entity_id') for more specificity (this warning may be suppressed after 10 occurrences)
if guess_is_literal else "column"
root 31/10/2018 06:16:59 PM INFO 1 feature_generators.py 553: Created table tasks for companies_entity_id
root 31/10/2018 06:16:59 PM INFO 1 feature_generators.py 560: Created table tasks for aggregation
root 31/10/2018 06:16:59 PM INFO 1 feature_generators.py 352: Created 2 tables
root 31/10/2018 06:16:59 PM INFO 1 multicore.py 78: Processing query tasks with 10 processes
root 31/10/2018 06:16:59 PM INFO 1 multicore.py 81: Processing features for companies_entity_id
root 31/10/2018 06:16:59 PM DEBUG 1 feature_generators.py 492: Executing feature generation query: DROP TABLE IF EXISTS "features"."companies_entity_id";
root 31/10/2018 06:16:59 PM DEBUG 1 feature_generators.py 492: Executing feature generation query: CREATE TABLE "features"."companies_entity_id" AS SELECT entity_id, '2016-11-01 00:00:00'::date AS as_of_date, count(*) AS companies_entity_id_all_total_count, count(*) FILTER (WHERE inspection_start_date >= '2016-11-01 00:00:00'::date - interval '100y') AS companies_entity_id_100y_total_count, count(*) FILTER (WHERE inspection_start_date >= '2016-11-01 00:00:00'::date - interval '1y') AS companies_entity_id_1y_total_count, count(*) FILTER (WHERE inspection_start_date >= '2016-11-01 00:00:00'::date - interval '1month') AS companies_entity_id_1month_total_count
FROM (select company as entity_id, * from semantic.events) as inspections
WHERE inspection_start_date < '2016-11-01 00:00:00'AND inspection_start_date >= '2015-01-01'::date GROUP BY entity_id
LIMIT :param_1
Experiment validation ran to completion with no errors
root 31/10/2018 06:17:00 PM ERROR 1 base.py 581: Run interrupted by uncaught exception
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 579, in run
self._run()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 564, in _run
self.generate_matrices()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 510, in generate_matrices
self.generate_preimputation_features()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 490, in generate_preimputation_features
self.process_query_tasks(self.feature_aggregation_table_tasks)
File "/usr/local/lib/python3.6/site-packages/triage/experiments/multicore.py", line 89, in process_query_tasks
n_processes=self.n_db_processes,
File "/usr/local/lib/python3.6/site-packages/triage/experiments/multicore.py", line 126, in parallelize
for result in pool.map(partially_bound_function, tasks):
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 288, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
raise self._value
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 450, in _handle_tasks
put(task)
File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 206, in send
self._send_bytes(_ForkingPickler.dumps(obj))
File "/usr/local/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'SerializableDbEngine'>: import of module <property object at 0x7ff0b18b01d8> failed
Traceback (most recent call last):
File "/code/run.py", line 122, in <module>
run_experiment()
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/code/run.py", line 112, in run_experiment
experiment.run()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 579, in run
self._run()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 564, in _run
self.generate_matrices()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 510, in generate_matrices
self.generate_preimputation_features()
File "/usr/local/lib/python3.6/site-packages/triage/experiments/base.py", line 490, in generate_preimputation_features
self.process_query_tasks(self.feature_aggregation_table_tasks)
File "/usr/local/lib/python3.6/site-packages/triage/experiments/multicore.py", line 89, in process_query_tasks
n_processes=self.n_db_processes,
File "/usr/local/lib/python3.6/site-packages/triage/experiments/multicore.py", line 126, in parallelize
for result in pool.map(partially_bound_function, tasks):
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 288, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
raise self._value
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 450, in _handle_tasks
put(task)
File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 206, in send
self._send_bytes(_ForkingPickler.dumps(obj))
File "/usr/local/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'SerializableDbEngine'>: import of module <property object at 0x7ff0b18b01d8> failed
```

This error happens independently of using `sqlalchemy.create_engine` or `traige.create_engine`. 

One point to note is that in the `run.py` we have:

```
@listens_for(Pool, "connect")
def assume_role(dbapi_con, connection_record):
    logging.debug(f"assuming role {os.environ['POSTGRES_ROLE']}")
    dbapi_con.cursor().execute(f"set role {os.environ['POSTGRES_ROLE']};")
```

Which potentially is the culprit for this beahaviour.

Switching to `SingleThreadExperiment` didn't solved the issue in the released `triage` on `pip`, but it is solved in `master`

**Comment by jesteria** [comment]
@nanounanue I am unable to reproduce. Can you point me to the codebase / implementation where this occurred?

**Comment by nanounanue** [comment]
It seems related to an old version of Debian, upgrading to `strecth`removed the error. I don't know why that happened.
