### ISSUE TITLE
Support n_jobs for models that allow them

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#61]
Currently, adding n_jobs to model parameters yields:

```
INFO:root:Training models
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    pipeline.run()
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/triage/pipeline.py", line 149, in run
    misc_db_parameters=dict(test=False)
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/triage/model_trainers.py", line 358, in train_models
    replace
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/triage/model_trainers.py", line 355, in <listcomp>
    model_id for model_id in self.generate_trained_models(
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/triage/model_trainers.py", line 295, in generate_trained_models
    for class_path, parameters in self._generate_model_configs(grid_config):
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/triage/model_trainers.py", line 88, in _generate_model_configs
    for parameters in ParameterGrid(parameter_config):
  File "/mnt/data/economic_development/san_jose_housing/venv/lib/python3.5/site-packages/sklearn/grid_search.py", line 116, in __iter__
    for v in product(*values):
TypeError: 'int' object is not iterable
```

**Comment by ecsalomon** [comment]
nvm, I didn't make it a list.
