### ISSUE TITLE
Triage's docker build failed

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#750]
Apparently the new versions of scikit-learn, scipy, and ~`pandas`~, `Pillow`  fails because the version of `numpy` is not supported.

```
  Building wheel for scipy (setup.py): started
  Building wheel for scipy (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vjmpt4j3/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vjmpt4j3/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l0d9v9x1
       cwd: /tmp/pip-install-vjmpt4j3/scipy/
  Complete output (9 lines):
  /tmp/pip-install-vjmpt4j3/scipy/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vjmpt4j3/scipy/setup.py", line 492, in <module>
      setup_package()
    File "/tmp/pip-install-vjmpt4j3/scipy/setup.py", line 468, in setup_package
      from numpy.distutils.core import setup
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vjmpt4j3/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vjmpt4j3/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-vjmpt4j3/scipy
  Complete output (11 lines):
  /tmp/pip-install-vjmpt4j3/scipy/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
  Building wheel for scikit-learn (setup.py): started
  Building wheel for scikit-learn (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vjmpt4j3/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vjmpt4j3/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0tw4exxs
       cwd: /tmp/pip-install-vjmpt4j3/scikit-learn/
  Complete output (15 lines):
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "/tmp/pip-install-vjmpt4j3/scikit-learn/setup.py", line 153, in get_numpy_status
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vjmpt4j3/scikit-learn/setup.py", line 250, in <module>
      setup_package()
    File "/tmp/pip-install-vjmpt4j3/scikit-learn/setup.py", line 240, in setup_package
      .format(numpy_req_str, instructions))
  ImportError: Numerical Python (NumPy) is not installed.
  scikit-learn requires NumPy >= 1.8.2.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
```

Probably the culprit is 

https://github.com/dssg/triage/blob/8a35185270e19d07adef48b9a110708cb5d02763/docker/requirements.txt#L1

**Comment by nanounanue** [comment]
Mmm the error persists. I will keep investigating
